version: 2

python:
  version: 3
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - sphinx
    - method: setuptools      
  system_packages: true

